#!/bin/bash
./scripts/code_dir.sh | xargs -I {} ./vendor/bin/php-cs-fixer fix {} --level=symfony --fixers=-psr0,-concat_without_spaces,-phpdoc_no_empty_return,-phpdoc_params,-phpdoc_short_description,-phpdoc_scalar,-unalign_double_arrow,-phpdoc_var_without_name
if [ -f tests/acceptance/AcceptanceTester.php ] ; then
  git checkout -- tests/acceptance/AcceptanceTester.php
fi
if [ -f tests/functional/FunctionalTester.php ] ; then
  git checkout -- tests/functional/FunctionalTester.php
fi
if [ -f tests/unit/UnitTester.php ] ; then
  git checkout -- tests/unit/UnitTester.php
fi
if [ -d tests/_support ] ; then
  git checkout -- tests/_support
fi
